// Code generated by "stringer -type=PluginType -linecomment"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InputPlugin-0]
	_ = x[FilterPlugin-1]
	_ = x[OutputPlugin-2]
}

const _PluginType_name = "inputfilteroutput"

var _PluginType_index = [...]uint8{0, 5, 11, 17}

func (i PluginType) String() string {
	if i < 0 || i >= PluginType(len(_PluginType_index)-1) {
		return "PluginType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PluginType_name[_PluginType_index[i]:_PluginType_index[i+1]]
}
